---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xie'peng.
--- DateTime: 2023/12/21 11:04
---参数1，优惠券id
local voucherId = ARGV[1]
---2,用户id
local userId = ARGV[2]
---1，库存key
local stockKey = 'seckill:stock:' .. voucherId
---2,订单id
local orderKey = 'seckill:order:' .. voucherId
---判断库存是否充足
if(tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end
---判断用户是否已经下单 SISMENMBER orderKey userId
--if(redis.call('sismember',orderKey,userId) == 1) then
--    ---存在
--    return 2
--end
---扣库存
redis.call('incrby',stockKey,-1)
---下单
redis.call('sadd',orderKey,userId)

return 0