---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xie'peng.
--- DateTime: 2023/12/20 17:48
---释放锁的lua脚本
---KEYS[1]是key;ARGV[1]是threadId
if(redis.call('get',KEYS[1]) == ARGV[1]) then---判断线程标识与锁中标识是否一致
    return redis.call('del',KEYS[1])---释放锁
end
return 0
